src/Entity/Articulo.php
<?php

namespace App\Entity;

use App\Repository\ArticuloRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticuloRepository::class)
 */
class Articulo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $talla;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $color;

    /**
     * @ORM\Column(type="float")
     */
    private $precio_uni;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTalla(): ?string
    {
        return $this->talla;
    }

    public function setTalla(string $talla): self
    {
        $this->talla = $talla;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getPrecioUni(): ?float
    {
        return $this->precio_uni;
    }

    public function setPrecioUni(float $precio_uni): self
    {
        $this->precio_uni = $precio_uni;

        return $this;
    }
}

src/Form/ArticuloType.php
<?php

namespace App\Form;

use App\Entity\Articulo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ArticuloType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('talla', ChoiceType::class,[
                'choices' => [
                    'xs' => 'XS',
                    's' => 'S',
                    'm' => 'M',
                    'l' => 'L',
                    'xl' => 'XL',
                    'xxl' => 'XXL',
                ]])
            ->add('color', ChoiceType::class,[
                'choices' => [
                    'blanco' => 'Blanco',
                    'negro' => 'Negro',
                    'rojo' => 'Rojo',
                    'verde' => 'Verde',
                    'azul' => 'Azul',
                ]])
            ->add('precio_uni')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Articulo::class,
        ]);
    }
}

src/Controller/ArticuloController.php
<?php

namespace App\Controller;

use App\Entity\Articulo;
use App\Form\ArticuloType;
use App\Repository\ArticuloRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/articulo")
 */
class ArticuloController extends AbstractController
{
    /**
     * @Route("/", name="articulo_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(ArticuloRepository $articuloRepository): Response
    {
        return $this->render('articulo/index.html.twig', [
            'articulos' => $articuloRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="articulo_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $articulo = new Articulo();
        $form = $this->createForm(ArticuloType::class, $articulo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($articulo);
            $entityManager->flush();

            return $this->redirectToRoute('articulo_index');
        }

        return $this->render('articulo/new.html.twig', [
            'articulo' => $articulo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articulo_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Articulo $articulo): Response
    {
        return $this->render('articulo/show.html.twig', [
            'articulo' => $articulo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="articulo_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Articulo $articulo): Response
    {
        $form = $this->createForm(ArticuloType::class, $articulo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('articulo_index');
        }

        return $this->render('articulo/edit.html.twig', [
            'articulo' => $articulo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articulo_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Articulo $articulo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$articulo->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($articulo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('articulo_index');
    }
}

templates/articulo/_delete_form.html.twig
<form method="post" action="{{ path('articulo_delete', {'id': articulo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ articulo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/articulo/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/articulo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Articulo{% endblock %}

{% block body %}
    <h1>Edit Articulo</h1>

    {{ include('articulo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('articulo_index') }}">back to list</a>

    {{ include('articulo/_delete_form.html.twig') }}
{% endblock %}

templates/articulo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articulo index{% endblock %}

{% block body %}
    <h1>Articulo index</h1>
{{ dump(usuario) }}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Talla</th>
                <th>Color</th>
                <th>Precio_uni</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for articulo in articulos %}
            <tr>
                <td>{{ articulo.id }}</td>
                <td>{{ articulo.talla }}</td>
                <td>{{ articulo.color }}</td>
                <td>{{ articulo.precioUni }}</td>
                <td>
                    <a href="{{ path('articulo_show', {'id': articulo.id}) }}">show</a>
                    <a href="{{ path('articulo_edit', {'id': articulo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('articulo_new') }}">Create new</a>
{% endblock %}

templates/articulo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Articulo{% endblock %}

{% block body %}
    <h1>Create new Articulo</h1>

    {{ include('articulo/_form.html.twig') }}

    <a href="{{ path('articulo_index') }}">back to list</a>
{% endblock %}

templates/articulo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articulo{% endblock %}

{% block body %}
    <h1>Articulo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ articulo.id }}</td>
            </tr>
            <tr>
                <th>Talla</th>
                <td>{{ articulo.talla }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ articulo.color }}</td>
            </tr>
            <tr>
                <th>Precio_uni</th>
                <td>{{ articulo.precioUni }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('articulo_index') }}">back to list</a>

    <a href="{{ path('articulo_edit', {'id': articulo.id}) }}">edit</a>

    {{ include('articulo/_delete_form.html.twig') }}
{% endblock %}